sudo: required # because we'll use docker
services:
  - docker # we want docker preinstalled
before_install: # a series of steps up to running tests
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # downoload and install the Google SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # will look at the default install folder of the SDK and source this file
  # a configuration that'll modify our shell inside our Travis CI
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # Authorization with the SDK and Google Cloud
  # equivalent to IAM on AWS, credentials in the .json file
  - gcloud auth activate-service-account --key-file service-account.json
